### ISSUE TITLE
One-click - signup error

### ISSUE THREAD

**Issue by VivienFuhrer** [ProxeusApp/proxeus-core#211]
### Subject of the issue
After I create the one-click install - If I try to signup another user as my root user - an error message is shown and it doesn't work.
![image](https://user-images.githubusercontent.com/25813493/111957440-4b967a80-8aec-11eb-9843-fec3b6ea55f2.png)

### Your environment
PC & Brave browser

### Steps to reproduce
Go to proxeus.startupcfo.ch and signup

### Expected behaviour
Signup without error

### Actual behaviour
Error message shown 
![image](https://user-images.githubusercontent.com/25813493/111957500-60730e00-8aec-11eb-825b-1b1813ee48d6.png)

**Comment by loleg** [comment]
Most likely, the problem is that you need to ensure that the **reply-to** e-mail address matches the domain which you configured for the Sparkpost key. We should make this clear in the documentation.

You can do this during the first step (System settings) when installing your instance, or in the administrative interface as shown here:

![Screenshot from 2021-03-22 11-17-19](https://user-images.githubusercontent.com/31819/111974921-48a58500-8b00-11eb-9cbf-44b772a36b5c.png)
