### ISSUE TITLE
Verification does not work without wallet

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#315]
If I am logged in with Metamask, verification works fine. The same document inside of Incognito mode, without Metamask, does not get verified. However, if I enable the Metamask extension without logging in, the document gets verified. In other words: web3 support is required for verification - and this should be the content of the error message. Also the documentation does [not make this clear](https://github.com/ProxeusApp/community/blob/master/handbook/handbook.md#42-verification).

### Your environment

Chrome

### Steps to reproduce

Go through the complete workflow to produce a verifiable document. Verify it with and without Metamask.

### Expected behaviour

Proxeus tells me to have my wallet installed.

### Actual behaviour

I get an error saying the document cannot be verified (see screenshot)

![Screenshot from 2023-06-26 13-47-59](https://github.com/ProxeusApp/proxeus-core/assets/31819/71280815-00ad-4fb8-b81c-e9de95f8604c)

**Comment by tafonina** [comment]
I checked and turned out if user is connected to Metamask with incorrect network - it shows Unverified for document (even if it is verified) -> it means that provider that is used for check is the one from metamask - but it should not depend on metamask - it can be created on base of network(chain id) and API key(infure), so the RPC URl can be easily generated and used to make a call to smart contract in order to check if document is verified or not.

**Comment by tafonina** [comment]
delegated task to @slavas490

**Comment by loleg** [comment]
As mentioned in the call, we may need to discuss:

- alternatives to Infura for getting this data
- option for the user to do an "offline" verification via Metamask anyway

**Comment by loleg** [comment]
Closing as done, thank you. The switching networks also works as expected.

We will follow up on the verification errors in #428
